name: release
on:
  release:
    types: [created]

jobs:
  test-before-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go for use with actions
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: test-before-release
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION env
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
      - uses: wangyoucao577/go-release-action@v1.33
        with:
          github_token: ${{ secrets.K64DEC_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.19"
          pre_command: export CGO_ENABLED=0
          build_flags: -v
          ldflags: -X 'github.com/laghoule/main/main.version=${{env.VERSION}}' -X 'github.com/laghoule/k64dec/main.gitCommit=${{ github.sha }}' -X 'github.com/laghoule/k64dec/main.gitRef=${{ github.ref }}'
          project_path: "cmd/"
          extra_files: LICENSE README.md
          retry: 10

  docker:
    runs-on: ubuntu-latest
    needs: test-before-release
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION env
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        env:
          VERSION: ${{ env.VERSION }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
        with:
          name: laghoule/k64dec
          username: ${{ github.actor }}
          password: ${{ secrets.K64DEC_TOKEN }}
          buildargs: VERSION, GIT_COMMIT, GIT_REF
          registry: ghcr.io
          tag_names: true
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        env:
          VERSION: ${{ env.VERSION }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
        with:
          name: laghoule/k64dec
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildargs: VERSION, GIT_COMMIT, GIT_REF
          tag_names: true